/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */

task<Exec>("runTests"){
    commandLine("pytest", "tests")
}

task<Exec>("build"){
    commandLine("python", "-m", "build")
}
